### PR TITLE
Expose recently graded ranges as admin config values

### PR DESCRIPTION
**Pull request by natecraddock**
This adds a new Config menu to the admin menu for changing admin/global
options in zygrader. This makes it easier to adjust these values without
needing to make a new zygrader release. This does NOT change the default
values from what they were in previous releases.

The class code menu was also moved to the new Config menu similar to the
class code override in the user preferences.

### CODE REVIEW

**Comment by natecraddock** [comment]
I am still not sure how github handles marges between branches, so I'd feel safer by merging manually from the commandline once accepted rather than using the green button here in the ui :)

**Comment by teiknsmith** [comment]
Longer range checks (>1hr) were awkward with just the minutes - I started getting a spinner impl in [spin-range-checks](/cs142ta/zygrader/tree/spin-range-checks) ([changes](https://github.com/cs142ta/zygrader/compare/dev...cs142ta:spin-range-checks)). I think if we go with that, storing the range as a formatted time string would be easier than a minutes digit, but I didn't go that far. I'd like thoughts first before doing that.

**Comment by natecraddock** [comment]
That's a really good idea. If we save it as a formatted time string, we will have to convert to minutes when storing in the SharedData for use in the locks, so we need to convert it somewhere. I think conversion to/from minutes the way you have done it in spin-range-checks is the best. If you're okay with it, I'll merge in the spinner and get this ready to push soon (I know Riley is waiting on a bugfix too)

**Comment by teiknsmith** [comment]
Makes sense that we'll need to convert somewhere, and I would agree then that what I've got in spin-range-checks is good, so you can do as proposed and merge that in

**Comment by natecraddock** [comment]
The whole flow here was wrong. Should have been a branch into dev not dev->master. It is accepted and finished so closing PR

**Pull request closed without merging**
